os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release

environment:
  matrix:
    - PYTHON: "C:\\Python27.10-x64"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"

install:
  ############################################################################
  # Install Ninja
  ############################################################################
  - choco install ninja

  ############################################################################
  # Install GYP
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - git clone https://chromium.googlesource.com/external/gyp.git
  - cd gyp
  - python setup.py install

before_build:
  - cd C:\projects\libpitaya
  - gyp --depth=. pomelo.gyp -f ninja --generator-output=build -Duse_sys_openssl=false -Dbuild_type=Release -Duse_xcode=false -Dbuild_cspomelo=true -Dbuild_for_windows=true

build_script:
  - cd build/out/Default
  - ninja