image: Visual Studio 2015

build:
  verbosity: detailed

configuration: Release

platform: x64

environment:
  nodejs_version: "Current"

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  #- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  ############################################################################
  # Install Ninja
  ############################################################################
  - choco install ninja
  #- choco install nasm

  ############################################################################
  # Install GYP
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - git clone https://chromium.googlesource.com/external/gyp
  - cd gyp
  - python setup.py install

before_build:
  - cd C:\projects\libpitaya
  - gyp --depth=. pomelo.gyp -f ninja --generator-output=build -Duse_sys_openssl=true -Dbuild_type=Release -Dbuild_cspomelo=true -Dbuild_for_windows=true

build_script:
  - cd build\out\Release_x64
  - ninja

deploy:
  description: 'Naice Release'
  provider: GitHub
  draft: true
  auth_token:
    secure: K7JbFSr7j5TSzbaFRrizO9MFQbYccfhldmMbgA5u23NROE5xKP4DcAfA1qDYjhz+ur/X8l4dogOTZn5AAgR/NMdELnPiU/6fyGJlzXa8lheYUoei5pUTlJCRX+YIKUalHc4rVFlhiS7NnVE4iZwK2xlgKyfImntAWrk4hgjaSoJB6x67I7pJVJM9aA+pDusoqR1G62PP99oPw29TEr9ttOTc/d0rgQFkjPs2v7vDttlPRqsfXdLXVDD/hz/nWB3AQ4Y3jMLPfrc17PWWixVnkzAPnB3Eoz3D4DQrXxYnMzM6Cis0haCVayEpu5ZoVwVBWNldtYui/qd/14xU/NBMFIn7ClB3WpzbfsLzBaa+pbNtr/CjPgRyBNP70D+cb3h2TDpvwCUvecImaC1RdNJSkqtqWYmryPcZMuDXQns91NRVLLXwnsTmw/CyXsdLP4/KMHgr/kERsb3Pde92L///mvcl/lDI/p/a8IZHRm9IDedqlG5aG2YEJUMoTXqCW7c9Ntpp9/bognLICff3twjkbDuHY9h2G+NA/dP3az52R3vA2I74BgcUDUINVUvGzScJc6nrhifHZugcR8mr8od8wPvIZReFzFv+ND0aquqtZRVb5kUl4RZkwwFfJ4vWB/bLVSxwT80k/83tKjEdC6L5rMO3QdE5thTEwa3rF0Bc35s=
  artifact: /.*\.dll(\.lib)?/
  on:
    appveyor_repo_tag: true

