image: Visual Studio 2015

build:
  verbosity: detailed

configuration: Release

install:
  ############################################################################
  # Install Ninja
  ############################################################################
  - choco install ninja

  ############################################################################
  # Install GYP
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - git clone https://chromium.googlesource.com/external/gyp.git
  - cd gyp
  - python setup.py install

  ############################################################################
  # Install zlib
  ############################################################################
  # get common functions
  - ps: >-
    $zlib_url = "https://zlib.net/zlib1211.zip"
    Invoke-WebRequest $zlib_url -OutFile "C:\projects\deps"
    Set-Location C:\projects\deps
    7z x zlib1211.zip -y -o zlib > NUL
    Set-Location zlib\contrib\vstudio\vc14
    msbuild zlibvc.sln
    Write-Host "zlib compiled successfully!"

  # fetch deps
  # - nuget install zlib-%tbs_tools%-%tbs_arch%-master -Source https://ci.appveyor.com/nuget/zlib-94hmpf3q011d
  # - move zlib* zlib
  # - del zlib\*.dll*
  # - ps: ls zlib\*_static.lib | % {move $_ ($_ -replace '_static', '') -force}

  # Enable command line toolset
  call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

before_build:
  - cd C:\projects\libpitaya
  - gyp --depth=. pomelo.gyp -f ninja --generator-output=build -Duse_sys_openssl=false -Dbuild_type=Release -Duse_xcode=false -Dbuild_cspomelo=true -Dbuild_for_windows=true

build_script:
  - cd build/out/Default
  - ninja
