os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release

environment:
  matrix:
      #- PYTHON: "C:\\Python27.10-x64"
      #PYTHON_VERSION: "2.7.10"
      #PYTHON_ARCH: "64"
    - tbs_arch: "x64"
      tbs_tools: "mingw"
      tbs_static_runtime: 0

install:
  ############################################################################
  # Install Ninja
  ############################################################################
  - choco install ninja

  ############################################################################
  # Install GYP
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - git clone https://chromium.googlesource.com/external/gyp.git
  - cd gyp
  - python setup.py install

  ############################################################################
  # Install zlib
  ############################################################################
  # get common functions
  - git clone https://github.com/imazen/gd-appveyor-helpers
  - ps: . .\gd-appveyor-helpers\appveyor_funcs.ps1
  
  # fetch deps
  - nuget install zlib-%tbs_tools%-%tbs_arch%-master -Source https://ci.appveyor.com/nuget/zlib-94hmpf3q011d
  - move zlib* zlib
  - del zlib\*.dll*
  - ps: ls zlib\*_static.lib | % {move $_ ($_ -replace '_static', '') -force}

before_build:
  - python --version
  - cd C:\projects\libpitaya
  - gyp --depth=. pomelo.gyp -f ninja --generator-output=build -Duse_sys_openssl=false -Dbuild_type=Release -Duse_xcode=false -Dbuild_cspomelo=true -Dbuild_for_windows=true

build_script:
  - cd build/out/Default
  - ninja
