image: Visual Studio 2015

build:
  verbosity: detailed

configuration: Release

environment:
  matrix:
    - arch: x64
      compiler: msys2-mingw
      backend: ninja

install:
  ############################################################################
  # Install Ninja
  ############################################################################
  - choco install ninja

  ############################################################################
  # Install GYP
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - git clone https://chromium.googlesource.com/external/gyp.git
  - cd gyp
  - python setup.py install

before_build:
  - cd C:\projects\libpitaya
  - gyp --depth=. pomelo.gyp -f ninja --generator-output=build -Duse_sys_openssl=false -Dbuild_type=Release -Dbuild_cspomelo=true -Dbuild_for_windows=true

build_script:
  - cd build/out/Default
  - ninja
  - dir
  # - cat libpitaya.vcxproj
  # - msbuild pomelo.sln /t:Build /p:Configuration=Release /p:Platform=Win32
    #- cd build/out/Default
    #- ninja
