image: Visual Studio 2017

build:
  verbosity: detailed

configuration: Release

environment:
  nodejs_version: "Current"
  matrix:
    - arch: x64
      compiler: msys2-mingw
      backend: ninja

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  ############################################################################
  # Install Ninja
  ############################################################################
  #- choco install ninja
  #- choco install strawberryperl
  #- choco install nasm

  ############################################################################
  # Install GYP
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
    #- git clone https://github.com/leohahn/gyp
  - git clone https://chromium.googlesource.com/external/gyp
  - cd gyp
  - python setup.py install

before_build:
  #- cd C:\projects\libpitaya\deps\openssl\openssl
  #- mkdir _build
  #- cd _build
  #- perl ..\Configure VC-WIN64A no-asm
  #- nmake
  #- nmake install

  - cd C:\projects\libpitaya
  - gyp --depth=. pomelo.gyp -Duse_sys_openssl=true -Dbuild_type=Release -Dbuild_cspomelo=true -Dbuild_for_windows=true

build_script:
    #- cd build/out/Default
    #- cat build.ninja
    #- ninja
    #- dir
  - dir
  - msbuild pomelo.sln
  # - cat libpitaya.vcxproj
  # - msbuild pomelo.sln /t:Build /p:Configuration=Release /p:Platform=Win32
    #- cd build/out/Default
    #- ninja
