language: c
compiler: clang
go:
  - '1.9.2'
os:
  - linux
  - osx
install: make setup-ci
script:
  - if [[ -n $TRAVIS_TAG ]]; then echo "travis tag is $TRAVIS_TAG"; fi
  - make build
sudo: required
addons:
  apt:
    update: true
before_deploy:
  - git config --local user.name "Travis Bot"
  - git config --local user.email "<>"
deploy:
  provider: releases
  draft: true
  #tag_name: $TRAVIS_TAG
  api_key:
    secure: "BL8ELjTuU86fTxuuDSB5hIz0UBpAa2wi4qgf7YzgX8wbZh/5K78DBRkS1It+jL/h0leNXr87KJ5XF1naMvVGqCjy5+7VXuqWTnhrF+9pOQdjFE6Ckwdr+p9xz33jct7KAXFR1+jgJpBzE3jP6ZJ4syAOXdHJEPmTETwpuXPbkd/bkzRlYkF0WkssbT8aI5MpfIDJI9UPjDboMUSRASY42gyqxCeMySSqtNSFPcJIVFwx+zfjqPdSTYyEK/hG9aNIX/TgPlcEjMwAIPn1pi7GPkdJrvttpBd33QIbHvJTT0BZJ7DtRU0sf1dasg7DDH1AJP2MO9fb9BFWB+USqbll/buV7Vs5sm7ZNdd83pLUzKk+3f9XrV5SwF4FzJ4p7sSVQkHsaaZuHBJnzV4GLPVI/gtCS2EWoAzSiynCp9PCVLUC5Auw6yn6263riy0Zt58ZLPPqU9BiJYfo0Y9kx8ywMAKHYhM+2aFuZi+Vj063rfW/8U6hymOAVV6H+WOqDQ0ap9KKnfB2sR/vhbqboxZHLctxYe4p51cpKQx9t7GQFiC219o2ypDuLQOjlgEsDbW8WGHS6x43x/Yod4RFmJTBkZcWUekn5k7lju7BFh/tGe0gxYgSsD+xyt+cieMjriJyCWNPDHIO6GX+cE8mZyVu8JhPt7fxkuhEI9XCx1bmbbM="
  file_glob: true
  file: build/output/*
  skip_cleanup: true
  on:
    repo: topfreegames/libpitaya
    branch: travis-integration
    tags: true
