language: c
compiler: clang
go:
  - '1.9.2'
os:
  - linux
  - osx
install: make setup-ci
script:
  - if [[ -n $TRAVIS_TAG ]]; then echo "travis tag is $TRAVIS_TAG"; fi
  - make build
sudo: required
addons:
  apt:
    update: true
before_deploy:
  - git config --local user.name "Travis Bot"
  - git config --local user.email "<>"
deploy:
  provider: releases
  draft: true
  #tag_name: $TRAVIS_TAG
  api_key:
    secure: "iQzPw4tZugNqtRTO3hCukAb21NbwhlaY/iU7c8NN+sJOSOAxn1swj5wqMe9OGgyHW044jYfQXFY0f8GXv8lNh/XfjedDeCYDPlimOeDFyeioJx8zJGak0oPsRy0LovNZxVKSCKtC93vu3Ydz1+UgB4Q5+JfQC0a3ipiTYDJjfb3xtW8zhT0I8+UNuHsWUhC6KxrvEBeGiK9eGnOja4dEheyvuPdYPVT1OfcjYZx6VyxgAhuAaG7Fi71c4su2MpuAdyCFAGAkOFzzQcytL3hpoEIDt+4l106jDKKBY43soKcv2SP0aQQ0S+6SZxXhTyE/GrTZxMjooQSiPFkr9/+OuWAn2WkA+QDWrUu19INeI9ieTSlv8DQIheknBxG5tj/k3DSyRD8CYPnqO9yDTsSIcfZn60f/58H6M7f8pyfzYw9I4BDvhgfahAxGloKzz/kXX9T32iU/VoLcnoNoQ0ZmokXudE02l06lHwYC4G8Fn26BwVJ6RG9pkEzw9OFf3/6+jB4uSXwv2NRdPgSM+fBClCNkYhGhZt5Fi59ZxyouyXXrDooGo/1DOaeQTPValm30SKF7LEwGLbQYhHpbp0mqYXB4FNRynztqXiOogc9P4gGdtVFM0pOIPUVjHY/ldS3/fXsWBrB7fIfi/v5uDKywhi3o48v8ulfEjSmq5/gdyWU="
  file_glob: true
  file: build/output/*
  skip_cleanup: true
  on:
    repo: topfreegames/libpitaya
    branch: travis-integration
    tags: true
